version: '3'

volumes:
  mongodb_volume:

services:
  mongodb:
    image: mongo
    restart: always
    volumes:
      - mongodb_volume:/data/db
    environment:
      - MONGO_INITDB_DATABASE=forms
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js
    ports:
      - 27017:27017

  form_finder:
    build: form_finder/
    restart: always
    depends_on:
      - mongodb
    ports:
      - 8088:8088